# .github/workflows/create-release.yaml
name: Create Release
on:
  pull_request:
    types: [closed]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: stairlingtechnologies/chromedriver

# Add these permissions for GHCR access
permissions:
  contents: read
  packages: write
  pull-requests: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Generate version and prepare database/SQLx data once
  prepare-build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate version
        id: version
        uses: ./.github/actions/generate-version
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: prepare-build
    outputs:
      image: ${{ steps.image.outputs.image }}
      digest: ${{ steps.build.outputs.digest }}
      version: ${{ needs.prepare-build.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup build environment
        id: build-env
        uses: ./.github/actions/setup-build-env
        with:
          version: ${{ needs.prepare-build.outputs.version }}
          registry: ${{ env.REGISTRY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}


      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=raw,value=${{ needs.prepare-build.outputs.version }}
            type=raw,value=latest

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          build-args: |
            VERSION=${{ needs.prepare-build.outputs.version }}
            VCS_REF=${{ steps.build-env.outputs.vcs-ref }}
            BUILD_DATE=${{ steps.build-env.outputs.build-date }}
            PROJECT_URL=${{ steps.build-env.outputs.project-url }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image
        id: image
        run: |
          echo "image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

  release-drafter:
    runs-on: ubuntu-latest
    needs: [ prepare-build, build ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          disable-autolabeler: false
          version: 'v${{ needs.prepare-build.outputs.version }}'
          tag: 'v${{ needs.prepare-build.outputs.version }}'
          name: 'v${{ needs.prepare-build.outputs.version }}'
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
